### PR TITLE
OD-391 [Fix] Improvement in appearance for LFD accessibility

### PR DESCRIPTION
**Pull request by AndrRyaz**
@sofiiakvasnevska 

## Issue

OD-391 https://weboo.atlassian.net/browse/OD-391

## Description

- Added needed styles for LFD components to fix bugs in appearance 

## Backward compatibility
This change is fully backward compatible.
## Reviewers
@upplabs-alex-levchenko @ivandevupp @YaroslavOvdii

### CODE REVIEW

**Review by tonytlwu — COMMENTED** [review]
This looks like it will add margins to places that didn't have margins before, and therefore changing how things look for the LFD layouts. Please share screenshots before and after this change so I can verify.

**Comment by AndrRyaz** [comment]
@tonytlwu hi, here is a link for screencast with changes - http://somup.com/creZ2ybUqf

**Comment by tonytlwu** [comment]
@AndrRyaz Thanks. I can see that without your changes, the blue focus outline is being cropped. This appears to only be a problem because the component is laid out to be sitting against the top edge.

This is unlikely to happen and when it does, I think it's an acceptable consequence of laying out the page as such.

When your solution is applied, even without focussing on the field, the search field position is moved from how it used to look. We don't want that kind of unnecessary move.

From your screencast, I'm more concerned that the focus outline for the bookmark icon is thinner than the focus outline for the search input. Can we address that?

**Comment by AndrRyaz** [comment]
@tonytlwu I heard you, I will now check if it is possible to correct what you said. And how do I understand that the selection is cropped is acceptable?

**Comment by AndrRyaz** [comment]
@tonytlwu here is a link to a new video (sorry, no voice), I tried to show that the styles is the same and I think it is because the search input has a border with red.

**Comment by tonytlwu** [comment]
@AndrRyaz The selection being cropped is acceptable because this is something that happens on all web pages if you choose to add box shadows around an item that sits on the edge.

The focus outline is usually applied with `outline`, but because that's not how we're implementing it, it's something we'll have to accept. Inputs should rarely be positioned near the edge of the screen because that's bad UI design so we don't need to worry about it.

**Comment by AndrRyaz** [comment]
@tonytlwu I understand so I can close this PR

**Pull request closed without merging**
